routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::group(['prefix' => 'location'], function() {
    Route::get('/', 'LocationController@index');
    Route::post('/store', 'LocationController@store')->name('location.store');
    Route::get('/{id}/subdelete', 'LocationController@sub_delete')->name('subloc.delete');
    Route::get('/{id}/delete', 'LocationController@delete')->name('location.delete');
});

Route::group(['prefix' => 'agent'], function() {
    Route::get('/', 'AgentController@index');
    Route::get('/add', 'AgentController@add');
    Route::post('/store', 'AgentController@store')->name('agent.store');
    Route::get('/{id}/edit', 'AgentController@edit')->name('agent.edit');
    Route::post('/{id}/update', 'AgentController@update')->name('agent.update');
    Route::get('/{id}/delete', 'AgentController@delete')->name('agent.delete');
    Route::get('/{id}/show', 'AgentController@show')->name('agent.show');

    Route::get('/get-sub-location','AgentController@getSubLocation');
});

Route::group(['prefix' => 'passenger'], function() {
    Route::get('/', 'ClientController@index');
    Route::get('/add', 'ClientController@add');
    Route::post('/store', 'ClientController@store')->name('passenger.store');
    Route::get('/{id}/edit', 'ClientController@edit')->name('passenger.edit');
    Route::post('/{id}/update', 'ClientController@update')->name('passenger.update');
    Route::get('/{id}/delete', 'ClientController@delete')->name('passenger.delete');
    Route::get('/{id}/view', 'ClientController@view')->name('passenger.view');
    Route::get('/get-sub-location','ClientController@getSubLocation');
});


Route::group(['prefix' => 'invoice'], function() {
    Route::get('/', 'InvoiceController@index');
    Route::get('/add', 'InvoiceController@add');
    Route::post('/store', 'InvoiceController@store')->name('invoice.store');
    Route::get('/{id}/edit', 'InvoiceController@edit')->name('invoice.edit');
    Route::post('/{id}/update', 'InvoiceController@update')->name('invoice.update');
    Route::get('/{id}/delete', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('/unitPrice','InvoiceController@unitPrice');
    Route::get('/agentID','InvoiceController@agentID');
    Route::get('/clientID','InvoiceController@clientID');
    Route::get('/{id}/view', 'InvoiceController@show')->name('invoice.view');
    Route::get('/{id}/refund', 'InvoiceController@refund')->name('invoice.refund');
    Route::post('/refund/store', 'InvoiceController@refund_store')->name('invoice.refund_store');
});

Route::group(['prefix' => 'settings'], function() {
    Route::get('/', 'SettingController@index');
    Route::get('/{id}/edit', 'SettingController@edit')->name('setting.edit');
    Route::post('/{id}/update', 'SettingController@update')->name('setting.update');

    Route::get('/visa-type', 'VisaTypeController@index');
    Route::post('/visa-type/store', 'VisaTypeController@store')->name('visa-type.store');
    Route::get('/visa-type/{id}/delete', 'VisaTypeController@delete')->name('visa-type.delete');

    Route::get('/country', 'CountryController@index');
    Route::post('/country/store', 'CountryController@store')->name('country.store');
    Route::get('/country/{id}/delete', 'CountryController@delete')->name('country.delete');

    Route::get('/currency-type', 'PaymentTypeController@index');
    Route::post('/currency-type/store', 'PaymentTypeController@store')->name('currency-type.store');
    Route::get('/currency-type/{id}/delete', 'PaymentTypeController@delete')->name('currency-type.delete');

    Route::get('/exname', 'ExpenseNameController@index');
    Route::post('/exname/store', 'ExpenseNameController@store')->name('exname.store');
    Route::get('/exname/{id}/delete', 'ExpenseNameController@delete')->name('exname.delete');
    Route::get('/exname/{id}/sub_delete', 'ExpenseNameController@sub_delete')->name('exname.sub_delete');
});

Route::group(['prefix' => 'visa'], function() {
    Route::get('/', 'VisaController@index');
    Route::get('/add', 'VisaController@add');
    Route::post('/store', 'VisaController@store')->name('visa.store');
    Route::get('/{id}/edit', 'VisaController@edit')->name('visa.edit');
    Route::post('/{id}/update', 'VisaController@update')->name('visa.update');
    Route::get('/{id}/delete', 'VisaController@delete')->name('visa.delete');
});

Route::group(['prefix' => 'package'], function() {
    Route::get('/', 'PackageController@index');
    Route::post('/store', 'PackageController@store')->name('package.store');
    Route::get('/{id}/delete', 'PackageController@delete')->name('package.delete');
    Route::get('/{id}/edit', 'PackageController@edit')->name('package.edit');
    Route::post('/{id}/update', 'PackageController@update')->name('package.update');

});

Route::group(['prefix' => 'bank'], function() {
    Route::get('/', 'BankController@index');
    Route::get('/add', 'BankController@add');
    Route::post('/store', 'BankController@store')->name('bank.store');
    Route::get('/{id}/edit', 'BankController@edit')->name('bank.edit');
    Route::post('/{id}/update', 'BankController@update')->name('bank.update');
    Route::get('/{id}/delete', 'BankController@delete')->name('bank.delete');
});


Route::group(['prefix' => 'accounts'], function() {
    Route::get('/', 'AccountsController@index');
    Route::post('/profitSearch', 'AccountsController@incomeSearch')->name('search.incomeSearch');

    Route::get('/expense', 'ExpenseController@index');
    Route::get('/expense/add', 'ExpenseController@add');
    Route::post('/expense/store', 'ExpenseController@store')->name('expense.store');
    Route::get('/{id}/expense/delete', 'ExpenseController@delete')->name('expense.delete');

    Route::get('/chartOfAccount', 'AccountsController@chartOfAccount');
    Route::post('/chartOfAccountAdd', 'AccountsController@chartOfAccountAdd')->name('chartOfAccount.add');
    Route::get('/parentID', 'AccountsController@parentID');
    Route::get('/child_id', 'AccountsController@child_id');
});


Route::group(['prefix' => '/'], function() {
     Route::resource('companyProfile', 'ProfileController');
   
});


Route::group(['prefix' => 'office'], function() {
    Route::get('/', 'ForeignOfficeController@index');
    Route::get('/add', 'ForeignOfficeController@add');
    Route::post('/store', 'ForeignOfficeController@store')->name('office.store');
    Route::get('/{id}/edit', 'ForeignOfficeController@edit')->name('office.edit');
    Route::post('/{id}/update', 'ForeignOfficeController@update')->name('office.update');
    Route::get('/{id}/delete', 'ForeignOfficeController@delete')->name('office.delete');

    Route::get('/remittance', 'RemittanceController@index');
    Route::post('/remittance/store', 'RemittanceController@store')->name('remittance.store');
    Route::get('/remittance/{id}/delete', 'RemittanceController@delete')->name('remittance.delete');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<!-- Mirrored from www.urbanui.com/salt/jquery/pages/samples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 13 Dec 2017 12:33:56 GMT -->
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>{{ config('app.name', 'Laravel') }}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{{ asset('assets/node_modules/mdi/css/materialdesignicons.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css') }}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="{{ asset('assets/node_modules/font-awesome/css/font-awesome.min.css') }}" />
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{ asset('assets/images/favicon.html') }}" />
</head>

<body class="sidebar-dark" id="app">
    @yield('content')
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{{ asset('assets/node_modules/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ asset('assets/node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
  <script src="{{ asset('assets/node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('assets/node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js') }}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{{ asset('assets/js/off-canvas.js') }}"></script>
  <script src="{{ asset('assets/js/hoverable-collapse.js') }}"></script>
  <script src="{{ asset('assets/js/misc.js') }}"></script>
  <script src="{{ asset('assets/js/settings.js') }}"></script>
  <!-- endinject -->
</body>


<!-- Mirrored from www.urbanui.com/salt/jquery/pages/samples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 13 Dec 2017 12:33:56 GMT -->
</html>

resources/views/layouts/footer.blade.php
<!-- plugins:js -->
<script src="{{ asset('assets/node_modules/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js') }}"></script>
<!-- endinject -->
<script src="{{ asset('assets/node_modules/datatables.net/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ asset('assets/node_modules/sweetalert2/dist/sweetalert2.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/dropify/dist/js/dropify.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Plugin js for this page-->
<script src="{{ asset('assets/node_modules/flot/jquery.flot.js') }}"></script>
<script src="{{ asset('assets/node_modules/flot/jquery.flot.resize.js') }}"></script>
<script src="{{ asset('assets/node_modules/flot/jquery.flot.categories.js') }}"></script>
<script src="{{ asset('assets/node_modules/flot/jquery.flot.pie.js') }}"></script>
<script src="{{ asset('assets/node_modules/rickshaw/vendor/d3.v3.js') }}"></script>
<script src="{{ asset('assets/node_modules/rickshaw/rickshaw.min.js') }}"></script>
<script src="{{ asset('assets/bower_components/chartist/dist/chartist.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/chartist-plugin-legend/chartist-plugin-legend.js') }}"></script>
<script src="{{ asset('assets/node_modules/chart.js/dist/Chart.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/jquery-validation/dist/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/node_modules/select2/dist/js/select2.min.js') }}"></script>

<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{ asset('assets/js/off-canvas.js') }}"></script>
<script src="{{ asset('assets/js/hoverable-collapse.js') }}"></script>
<script src="{{ asset('assets/js/misc.js') }}"></script>
<script src="{{ asset('assets/js/settings.js') }}"></script>
<!-- endinject -->
<script src="{{ asset('assets/js/data-table.js') }}"></script>
<script src="{{ asset('assets/js/alerts.js') }}"></script>
<script src="{{ asset('assets/js/dropify.js') }}"></script>
<script src="{{ asset('assets/js/form-validation.js') }}"></script>

<!-- Custom js for this page-->
<script src="{{ asset('assets/js/dashboard_1.js') }}"></script>
<!-- End custom js for this page-->
<script src="{{ asset('assets/js/formpickers.js') }}"></script>
<script src="{{ asset('assets/js/form-addons.js') }}"></script>
<script>
    $("#year").datepicker({
        format: "yyyy",
        viewMode: "years",
        minViewMode: 2,
        autoclose: true
    });
    $(".datepickernew").datepicker({
        format: "dd-mm-yyyy",
        autoclose: true
    });
</script>
<script>
function printContent(el){
var restorepage = $('body').html();
var printcontent = $('.' + el).clone();
$('body').empty().html(printcontent);
window.print();
$('body').html(restorepage);
}
</script>
</body>

</html>

resources/views/layouts/head.blade.php
<!DOCTYPE html>
<html  lang="{{ str_replace('_', '-', app()->getLocale()) }}">


<!-- Mirrored from www.urbanui.com/salt/jquery/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 13 Dec 2017 12:31:57 GMT -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $title }} | {{ config('app.name', 'Tours & Travels') }}</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ asset('assets/node_modules/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css') }}">
    <!-- endinject -->
    <link rel="stylesheet" href="{{ asset('assets/node_modules/select2/dist/css/select2.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/node_modules/select2-bootstrap-theme/dist/select2-bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/node_modules/sweetalert2/dist/sweetalert2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/node_modules/font-awesome/css/font-awesome.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/node_modules/dropify/dist/css/dropify.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" />
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ asset('assets/node_modules/rickshaw/rickshaw.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/bower_components/chartist/dist/chartist.min.css') }}" />
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ asset('assets/images/favicon.html') }}" />
</head>
<body class="sidebar-dark">

@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif

resources/views/layouts/sidebar.blade.php
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
 <!--   <div class="user-info">
        <div class="profile">
            <img src="{{ asset('assets/images/user/ritesh.jpg')}}" alt="User Profile Picture" width="47">
        </div>
        <div class="details">
            <p class="user-name">{{ Auth::user()->name }}</p>
            <p class="designation">Manager</p>
        </div>
    </div>-->
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/dashboard') }}">
                <i class="mdi mdi-gauge menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#bookingSubmenu" aria-expanded="false" aria-controls="bookingSubmenu">
                <i class="mdi mdi-clipboard-text menu-icon"></i>
                <span class="menu-title">Invoice</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="bookingSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/invoice') }}">All Invoice</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/invoice/add') }}">Add Invoice</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ url('/package') }}">
                <i class="mdi mdi-package-variant menu-icon"></i>
                <span class="menu-title">Package</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#agentSubmenu" aria-expanded="false" aria-controls="agentSubmenu">
                <i class="mdi mdi-account-multiple-outline menu-icon"></i>
                <span class="menu-title">Agent</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="agentSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/agent') }}">All Agent</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/agent/add') }}">Add Agent</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/location') }}">Location</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#clientSubmenu" aria-expanded="false" aria-controls="clientSubmenu">
                <i class="mdi mdi-account-outline menu-icon"></i>
                <span class="menu-title">Passenger</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="clientSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/passenger') }}">All Passenger</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/passenger/add') }}">Add Passenger</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#visaSubmenu" aria-expanded="false" aria-controls="visaSubmenu">
                <i class="mdi mdi-web menu-icon"></i>
                <span class="menu-title">Visa Application</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="visaSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/visa') }}">All Visa Application</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/visa/add') }}">Add Visa Application</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#officeSubmenu" aria-expanded="false" aria-controls="officeSubmenu">
                <i class="mdi mdi mdi-earth menu-icon"></i>
                <span class="menu-title">Foreign Office</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="officeSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/office') }}">All Foreign Office</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/office/add') }}">Add Foreign Office</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/office/remittance') }}">Foreign Remittance</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#bankSubmenu" aria-expanded="false" aria-controls="bankSubmenu">
                <i class="mdi mdi-bank menu-icon"></i>
                <span class="menu-title">Bank</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="bankSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/bank') }}">All Bank</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/bank/add') }}">Add Bank</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#accountsSubmenu" aria-expanded="false" aria-controls="accountsSubmenu">
                <i class="mdi mdi-cash-usd menu-icon"></i>
                <span class="menu-title">Accounts</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="accountsSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/accounts') }}">Income Statement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/accounts/expense/add') }}">Add Expense</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ url('/accounts/expense') }}">All Expense</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ url('/accounts/chartOfAccount') }}">Chart Of Account</a>
                    </li>
                </ul>
            </div>
        </li>


               <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#CompanySubmenu" aria-expanded="false" aria-controls="bankSubmenu">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Company Profile</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="CompanySubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('companyProfile.create') }}">Add Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('companyProfile.index') }}">View Profile</a>
                    </li>
                </ul>
            </div>
        </li>



        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#settingSubmenu" aria-expanded="false" aria-controls="settingSubmenu">
                <i class="mdi mdi-settings menu-icon"></i>
                <span class="menu-title">Settings</span>
                <i class="mdi mdi-chevron-down menu-arrow"></i>
            </a>
            <div class="collapse" id="settingSubmenu">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/settings') }}">Company Settings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/settings/currency-type') }}">Payment Type</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/settings/visa-type') }}">Visa Type</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/settings/country') }}">Country</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/settings/exname') }}">Expense</a>
                    </li>
                </ul>
            </div>
        </li>

       

    </ul>
</nav>